# Generated by Django 4.0.6 on 2022-08-12 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_reels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reels',
            new_name='Reel',
        ),
    ]
